apiVersion: apps/v1
kind: ReplicationController
metadata:
  name: myapp
  labels:
    app: myapp
    type: frontend
spec:
  template:
    metadata:
      name: myapp_replicationcontroller
      labels:
        app: myapp
        type: frontend
    spec:
      containers:
        - name: myapp
          image: nginx:1.14.2
          ports:
            - containerPort: 80
