apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: apache-role
  namespace: apache
rules:
  - apiGroups: ["", "apps", "authorization.k8s.io", "batch"] # This rule allows access to core resources, apps, authorization, and batch API groups
    resources: ["pods", "services", "deployments", "hpas"] # This rule allows access to pods, services, deployments, and horizontal pod autoscalers
    verbs: ["get", "delete", "list"] # This rule allows the user to get, delete, and list the specified resources